[project]
name = "biyesheji"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf>=3.0.0",
    "Pillow>=10.0.0",
    "datasets>=2.0.0",
    "playwright>=1.57.0",
    "bs4>=0.0.2",
]
